[build]
command = "rm -rf bin obj && dotnet restore && dotnet publish -c Release -o ./publish"
output = "./publish"

[deploy]
startCommand = "echo 'Checking JWT_KEY: $JWT_KEY' && dotnet AuthTodoApp.dll"

[variables]
JWT_KEY = { must_be_set = true }
JWT_ISSUER = "YesList"
JWT_AUDIENCE = "YesUsers"
PORT = "8080"