[build]
command = "dotnet restore && dotnet publish -c Release -o ./publish"
output = "./publish"

[deploy]
startCommand = "dotnet AuthTodoApp.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
DOTNET_ROOT = "/app"