[build]
command = "dotnet restore && dotnet publish -c Release -o ./publish"
output = "./publish"

[deploy]
startCommand = "dotnet AuthTodoApp.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "8080"
DATABASE_URL = "postgresql://postgres:tipajupORvvQGJnaTmYgHNJFeYWCYxXU@gondola.proxy.rlwy.net:25695/railway"
JWT_KEY = "ThisIsASecretKeyForJwtTokenDontShare"       
JWT_ISSUER = "YesList"
JWT_AUDIENCE = "YesUsers"